---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkauthentications.policy.linkerd.io
  annotations:
    {{ include "partials.annotations.created-by" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    linkerd.io/control-plane-ns: {{.Release.Namespace}}
spec:
  group: policy.linkerd.io
  scope: Namespaced
  names:
    kind: NetworkAuthentication
    plural: networkauthentications
    singular: networkauthentication
    shortNames: []
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              description: >-
                TODO
              type: object
              required: [networks]
              properties:
                networks:
                  description: >-
                    The list of networks that this authentication applies to.
                  type: array
                  items:
                    type: object
                    required: [cidr]
                    properties:
                      cidr:
                        description: >-
                          The CIDR of the network that this authentication
                        type: string
                      except:
                        type: array
                        items:
                          type: string
